### PR TITLE
多余的空格

### PR DESCRIPTION
**Pull request by SolidBlock-cn**

### CODE REVIEW

**Comment by SolidBlock-cn** [comment]
所以这个pr没有合并就直接关闭了吗

**Comment by lexoooooo** [comment]
Oh, sorry! I just missed this PR mistakenly because I run `git push --force` for fixing some commit email error.You can open a PR again,thank you.

**Comment by lexoliu** [comment]
> 所以这个pr没有合并就直接关闭了吗

Oh, sorry! I just missed this PR mistakenly because I run git push --force for fixing some commit email error.You can open a PR again,thank you.

**Comment by SolidBlock-cn** [comment]
好像没法reopen了。但我已经把我的分支更新了。

**Comment by lexoliu** [comment]
> 好像没法reopen了。但我已经把我的分支更新了。

Yes, because `git push --force` has overwritten the old commit of this repository . You must fork this repository again.What's more, feel free to drop me a message! [me@lexo.cool](mailto:me@lexo.cool)

**Pull request closed without merging**
